"""add author column to scripts

Revision ID: 321a31b9a100
Revises: e9cbf8f5680e
Create Date: 2025-10-27 18:18:13.339483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "321a31b9a100"
down_revision: Union[str, None] = "e9cbf8f5680e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scripts", sa.Column("author", sa.String(), nullable=True))
    op.alter_column(
        "scripts",
        "content",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_constraint("scripts_user_id_fkey", "scripts", type_="foreignkey")
    op.drop_column("scripts", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scripts", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "scripts_user_id_fkey",
        "scripts",
        "user",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "scripts",
        "content",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("scripts", "author")
    # ### end Alembic commands ###
