"""add lessons

Revision ID: 39c45501737e
Revises: 08290f46df91
Create Date: 2025-10-11 01:44:42.842821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39c45501737e'
down_revision: Union[str, None] = '08290f46df91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('breakpoints', 'correct_choice',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='correct_choice::integer'
               )
    op.add_column('lesson_videos', sa.Column('index', sa.Integer(), nullable=False))
    op.add_column('lesson_videos', sa.Column('breakpoints', sa.JSON(), nullable=True))
    op.drop_column('lesson_videos', 'order_index')
    op.drop_column('lesson_videos', 'created_at')
    op.add_column('lessons', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key(None, 'lessons', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lessons', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'user_id')
    op.add_column('lesson_videos', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('lesson_videos', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('lesson_videos', 'breakpoints')
    op.drop_column('lesson_videos', 'index')
    op.alter_column('breakpoints', 'correct_choice',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
