"""whatever

Revision ID: 467a4d3739d4
Revises: 96f111e087b0
Create Date: 2025-11-19 23:58:45.855090

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "467a4d3739d4"
down_revision: Union[str, None] = "96f111e087b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
