"""Apply patches

Revision ID: c4aa1939eda6
Revises: 17cccd558a93
Create Date: 2025-11-21 00:24:08.891805

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c4aa1939eda6"
down_revision: Union[str, None] = "17cccd558a93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
